apiVersion: apps/v1
kind: Deployment
metadata:
  name: objectstorage-controller
  labels:
    run: objectstorage-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: objectstorage-controller
  template:
    metadata:
      labels:
        app: objectstorage-controller
    spec:
      containers:
        - name: objectstorage-controller
          image: quay.io/containerobjectstorage/objectstorage-controller:latest
          imagePullPolicy: IfNotPresent

